<?php
/**
 * Created by PhpStorm.
 * User: cronfy
 * Date: 18.06.18
 * Time: 13:04
 */

namespace cronfy\library\backend\widgets\HtmlEditorWidget;

use dosamigos\ckeditor\CKEditor;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\widgets\InputWidget;

class HtmlEditorWidget extends InputWidget
{

    public static function widget($config = [])
    {
        $config = ArrayHelper::merge([
                'preset' => 'custom',
                'clientOptions' =>
                    array_merge(
                        Json::decode('{"toolbarGroups":[{"name":"clipboard","groups":["clipboard","undo"]},{"name":"editing","groups":["find","selection","spellchecker","editing"]},{"name":"forms","groups":["forms"]},{"name":"basicstyles","groups":["basicstyles","cleanup"]},{"name":"paragraph","groups":["list","indent","blocks","align","bidi","paragraph"]},{"name":"links","groups":["links"]},{"name":"insert","groups":["insert"]},"/",{"name":"styles","groups":["styles"]},{"name":"colors","groups":["colors"]},{"name":"tools","groups":["tools"]},{"name":"others","groups":["others"]},{"name":"about","groups":["about"]},{"name":"document","groups":["mode","document","doctools"]}],"removeButtons":"Save,NewPage,Templates,Cut,Copy,Paste,PasteText,PasteFromWord,Find,Replace,SelectAll,Scayt,Form,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,Subscript,Superscript,Blockquote,CreateDiv,JustifyBlock,BidiLtr,BidiRtl,Language,Flash,Smiley,PageBreak,Iframe,About"}'),
                        [ 'allowedContent' => true,]
                    ),
        ], $config);

        return CKEditor::widget($config); // TODO: Change the autogenerated stub
    }
}
